// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmRxf-8n4NjkTb5FEKI7QvsYnojOCtHMk',
    appId: '1:1030586656828:web:bb7d9a54029a466dfd7b39',
    messagingSenderId: '1030586656828',
    projectId: 'mylastapp-c7933',
    authDomain: 'mylastapp-c7933.firebaseapp.com',
    storageBucket: 'mylastapp-c7933.appspot.com',
    measurementId: 'G-7YM53KR7LK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPNNrJcy9z_Esn4MHQYF_3l4wvIca5fdw',
    appId: '1:1030586656828:android:e8d1f3cb2f9d27d7fd7b39',
    messagingSenderId: '1030586656828',
    projectId: 'mylastapp-c7933',
    storageBucket: 'mylastapp-c7933.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2R7W_Mbyk5SCm0hkfzY8wQj0OmmlXaGU',
    appId: '1:1030586656828:ios:c8a5bb647e0baf20fd7b39',
    messagingSenderId: '1030586656828',
    projectId: 'mylastapp-c7933',
    storageBucket: 'mylastapp-c7933.appspot.com',
    iosBundleId: 'com.example.finalYearProject18',
  );
}
